# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        app: null
        #user:
        #    persistence:
        #        driver: orm
        #        model: App\Entity\User
        #        provider: ~
        #        finder: ~
        #    properties:
        #        Name: ~
        #        email: ~
#
        #artist:
        #    persistence:
        #        driver: orm
        #        model: App\Entity\Artist
        #        provider: ~
        #        finder: ~
        #    properties:
        #        Name: ~
#
        #radio:
        #    persistence:
        #        driver: orm
        #        model: App\Entity\Radio
        #        provider: ~
        #        finder: ~
        #    properties:
        #        Title: ~
#
        #teletime:
        #    persistence:
        #        driver: orm
        #        model: App\Entity\Teletime
        #        provider: ~
        #        finder: ~
        #    properties:
        #        Title: ~
#
        #windowlicker:
        #    persistence:
        #        driver: orm
        #        model: App\Entity\Windowlicker
        #        provider: ~
        #        finder: ~
        #    properties:
        #        Title: ~
#
        #location:
        #    persistence:
        #        driver: orm
        #        model: App\Entity\Location
        #        provider: ~
        #        finder: ~
        #    properties:
        #        Name: ~
#
        #tag:
        #    persistence:
        #        driver: orm
        #        model: App\Entity\Tag
        #        provider: ~
        #        finder: ~
        #    properties:
        #        Name: ~
