name: Symfony

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
      with:
        php-version: '8.1'

    - uses: actions/checkout@v3

    - name: Copy Environment Variables
      run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install Composer
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install NPM
      run: npm install

    - name: Build Webpack
      run: npx webpack

    - name: Create Database
      run: |
        mkdir -p data
        touch data/data.db
  
    # - name: Execute tests (Unit and Feature tests) via PHPUnit
    #   env:
    #     DATABASE_URL: sqlite:///%kernel.project_dir%/data/data.db
    #   run: vendor/bin/phpunit
